### ISSUE TITLE
Missed modul

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_comments#10]
On save stream-cmt chars:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/user/.cudatext/py/cuda_comments/cd_comments.py", line 86, in edit_strcomment_chars
    open(usr_lexs_json, 'w').write(json.dumps(usr_lexs, indent=2))
NameError: name 'json' is not defined
```

**Comment by kvichans** [comment]
Да, перестарался с обрезанием :)
